# Generated by Django 4.1 on 2022-10-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlackModel',
        ),
    ]
